# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

workspace(name = "score_toolchains_gcc_tests")
local_repository(
    name = "score_toolchains_gcc",
    path = "..",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

load("@score_toolchains_gcc//:deps.bzl", "toolchain_gcc_dependencies")
toolchain_gcc_dependencies()

load("@score_toolchains_gcc//rules:gcc.bzl", "gcc_toolchain")
gcc_toolchain(
    name = "gcc_toolchain",
    gcc_repo = "gcc_toolchain_gcc",
    extra_features = [
        "minimal_warnings",
        "treat_warnings_as_errors",
    ],
    warning_flags = {
        "minimal_warnings": ["-Wall", "-Wno-error=deprecated-declarations"],
        "strict_warnings": ["-Wextra", "-Wpedantic"],
        "treat_warnings_as_errors": ["-Werror"],
    },
)
